### PR TITLE
Crafting Parts

### PR DESCRIPTION
**Pull request by terezi4real**
## About the PR

Merges what ive been working on, sprites and recipes need redoing but thats for later terezi. 

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a lot
- add: Tiny bomb

### CODE REVIEW

**Comment by terezi4real** [comment]
tfw you thought it was fine and then the checks die one by one

**Comment by sTiKyt** [comment]
> tfw you thought it was fine and then the checks die one by one

Don't worry about checks, i'll just reorganize it a bit and then gonna merge

**Comment by sTiKyt** [comment]
Also this one it missing it's machine
image

**Review by sTiKyt — APPROVED** [review]
Dang bro, had to change A LOOOOT,  but it should be good now

**Pull request merged**
